### ISSUE TITLE
Stable tag

### ISSUE THREAD

**Issue by adamv** [nothingmuch/git-svn-abandon#2]
Can we get a tag for a non-HEAD version of this?

**Comment by bfontaine** [comment]
@adamv Why did you close this issue?

**Comment by adamv** [comment]
Because it was two years with no reply.
(I'm unsubscribing from this ticket after this reply as well.)

**Comment by bfontaine** [comment]
@nothingmuch Ping?

**Comment by nothingmuch** [comment]
Sorry I had been on a long hiatus from coding when this issue was opened.

I have never put in the time to make a proper release of this repository, and unfortunately I think I'm underqualified now (I've repressed all of my SVN knowlege).

So while I'd be happy to tag, or do any administrativa as necessary to help, I'm not sure I can really do meaningful work to improve the state of the project as a whole, if this is being depended on.

With that caveat in mind, what should I actually do? Just tag head with some usable stable identifier for you to refer to?

**Comment by bfontaine** [comment]
> With that caveat in mind, what should I actually do? Just tag head with some usable stable identifier for you to refer to?

Yes that would be sufficient for us. Thank you!

**Comment by nothingmuch** [comment]
added 0.0.1 as an arbitrary initial version

there are no changes to the code tree, just an annotated tag

**Comment by nothingmuch** [comment]
https://github.com/nothingmuch/git-svn-abandon/releases/tag/0.0.1

**Comment by bfontaine** [comment]
Thank you!
